#
# Vivado (TM) v2014.4 (64-bit)
#
# project.tcl: Tcl script for re-creating project 'project_1'
#
# Generated by Vivado on Sun Oct 18 19:30:00 CST 2015
# IP Build 1070531 on Tue Nov 18 01:10:18 MST 2014
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "/home/xilinxfae/myData/work/microZed/linux_interrupt/project_1/project_1.srcs/sources_1/bd/design_1/design_1.bd"
#    "/home/xilinxfae/myData/work/microZed/linux_interrupt/project_1/project_1.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Create project
create_project project_1 ./project_1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [get_projects project_1]
set_property "board_part" "em.avnet.com:microzed_7010:part0:1.0" $obj
set_property "default_lib" "xil_defaultlib" $obj
set_property "simulator_language" "Mixed" $obj

# Create Block Design
source bd.tcl

# Genreate wrapper for block design
add_files -norecurse [make_wrapper -files [get_files -filter {FILE_TYPE == "Block Designs"}] -top]

# Generate bitstream
reset_run synth_1
launch_runs impl_1 -to_step write_bitstream

# Export with Bitstream
